[[raincatcher-documentation]]
= Raincatcher Documentation


[[overview]]
== Overview

This repository contains useful documentation for developers wishing to
use Raincatcher modules and demo apps.

[[getting-started-with-the-demo-solution]]
== Getting Started With The Demo Solution

The link:getting-started.adoc[Getting Started With The Demo Solution
Guide] demonstrates how to use the Red Hat Mobile Application Platform
(RHMAP) to import the demo solution and get it up and running.

[[demo-solution-architecture]]
== Demo Solution Architecture

The link:demo-solution-architecture.adoc[Demo Solution Architecture]
document describes the architecture of the demo solution and how it
integrates with Raincatcher modules.

[[running-the-demo-solution-locally]]
== Running The Demo Solution Locally

The link:running-locally.adoc[Running The Demo Raincatcher Solution
Locally] guide explains how to get the Raincatcher demo solution running
on your local development machine. This is targeted at developers that
wish to extend the existing functionality of Raincatcher modules and
demo apps.

[[integrating-a-new-module-into-the-demo-solution]]
== Integrating A New Module Into The Demo Solution

The link:module-integration.adoc[Module Integration] guide explains how a
new module can be introduced to the overall solution to provide extra
functionality.
