[[running-the-demo-raincatcher-solution-locally]]
= Running The Demo Raincatcher Solution Locally

[[requirements]]
== Requirements

[[rhmap]]
=== RHMAP

The demo solution currently requires an instance of RHMAP. It can be a local or remote instance of RHMAP, but must be configured as outlined in the Raincatcher link:getting-started.adoc[Getting Started Guide] so that the local *raincatcher-demo-cloud* app can access the following RHMAP features:

* Forms
* Themes
* Drag & Drop App Configuration


[[mongodb]]
=== MongoDB

The *raincatcher-demo-cloud* app and *raincatcher-demo-auth* app requires a local running MongoDB instance. See the link:https://docs.mongodb.com/manual/installation/[MongoDB Installation Guide] for details on how to install MongoDB.

[[redis]]
=== Redis

The *raincatcher-demo-cloud* app requires a local running instance of Redis. See the link:https://redis.io/topics/quickstart[Redis Quick Start Guide] for details on how to install Redis, or use your system's package manager.

[[ruby]]
=== Ruby 

To use the Raincatcher CLI Tool, described later, you need to install link:https://www.ruby-lang.org/en/documentation/installation/[Ruby]. If the CLI tool is not required, you do not need to install Ruby.


[[install-raincatcher-cli-and-clone]]
== Install Raincatcher CLI and Clone Repositories
The link:https://github.com/feedhenry-raincatcher/raincatcher-cli[Raincatcher CLI Tool] is a useful tool for getting set up with all of the Raincatcher modules and demo apps. Follow the steps in the README to clone, install, and link all of the Raincatcher modules.

=== Configure Environment Variables

In order to communicate with RHMAP and the local authentication service, several environment variables need to be configured. You can find the values in RHMAP -> Projects -> _Project name given in link:getting-started.adoc[Getting Started Guide] -> WFM Demo Cloud App -> Environment Variables -> System Environment Variables.

These environment variables can be placed in the `raincatcher-demo-cloud/Gruntfile.js` file in the Demo Cloud App.		 

[source,javascript]
----
{
  ...
  env: {
    local: {
      FH_APPNAME: "<FH_APPNAME value>",
      FH_DOMAIN: "<FH_DOMAIN value>",
      FH_ENV: "<FH_ENV value>",
      FH_INSTANCE: "<FH_INSTANCE value>",
      FH_MBAAS_ENV_ACCESS_KEY: "<FH_MBAAS_ENV_ACCESS_KEY value>",
      FH_MBAAS_HOST: "<FH_MBAAS_HOST value>",
      FH_MBAAS_PROTOCOL: "<FH_MBAAS_PROTOCOL value>",
      FH_WIDGET: "<FH_WIDGET value>",
      FH_APP_API_KEY: "<FH_APP_API_KEY value>",

      // This value can be found in `raincatcher-demo-cloud/Gruntfile.js`
      // in the FH_SERVICE_MAP environment variable
      WFM_AUTH_GUID: "iidn3tvprs62asdebat5m3eg"
    }
  }
  ...
}
----

[[running-the-applications]]
== Running The Applications

To start the applications:

[source,javascript]
----
wfm start
----
